# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vir/Lab8/Lab8.cache/wt [current_project]
set_property parent.project_path /home/vir/Lab8/Lab8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib -sv {
  /home/vir/Lab8/Lab8.srcs/sources_1/imports/new/xycounter.sv
  /home/vir/Lab8/Lab8.srcs/sources_1/new/display640x480.sv
  /home/vir/Lab8/Lab8.srcs/sources_1/new/vgatimer.sv
  /home/vir/Lab8/Lab8.srcs/sources_1/new/vgadisplaydriver.sv
}
read_xdc /home/vir/Lab8/Lab8.srcs/constrs_1/new/vgadisplaydriver.xdc
set_property used_in_implementation false [get_files /home/vir/Lab8/Lab8.srcs/constrs_1/new/vgadisplaydriver.xdc]

synth_design -top vgadisplaydriver -part xc7a100tcsg324-1
write_checkpoint -noxdef vgadisplaydriver.dcp
catch { report_utilization -file vgadisplaydriver_utilization_synth.rpt -pb vgadisplaydriver_utilization_synth.pb }
