# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vir/LabProject/LabProject.cache/wt [current_project]
set_property parent.project_path /home/vir/LabProject/LabProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog {
  /home/vir/LabProject/LabProject.srcs/sources_1/new/initfile.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/memory.sv
  /home/vir/Lab8/Lab8.srcs/sources_1/new/display640x480.sv
}
set_property file_type "Verilog Header" [get_files /home/vir/LabProject/LabProject.srcs/sources_1/new/initfile.sv]
set_property file_type "Verilog Header" [get_files /home/vir/LabProject/LabProject.srcs/sources_1/new/memory.sv]
set_property file_type "Verilog Header" [get_files /home/vir/Lab8/Lab8.srcs/sources_1/new/display640x480.sv]
read_mem {
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/Downloads/bmem_init.txt
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/Downloads/smem_init.txt
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/Downloads/dmem_init.txt
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/Downloads/imem_init.txt
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/Downloads/regd_init.txt
}
read_verilog -library xil_defaultlib -sv {
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/fulladder.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/adder.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/shifter.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/comparator.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/logical.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/addsub.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/new/xycounter.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/register_file.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/ALU.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/imports/new/hexto7seg.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/keyboard.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/smem.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/new/vgatimer.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/bitmapmem.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/datapath.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/controller.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/dmem.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/display8digit.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/clockdiv.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/new/memIO.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/new/vgadisplaydriver.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/new/debouncer.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/mips.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/imem.sv
  /home/vir/LabProject/LabProject.srcs/sources_1/imports/sources_1/new/top.sv
}
read_xdc /home/vir/LabProject/LabProject.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files /home/vir/LabProject/LabProject.srcs/constrs_1/new/master.xdc]

synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
