# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/vir/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path /home/vir/Lab6/Lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib -sv {
  /home/vir/Lab6/Lab6.srcs/sources_1/imports/new/hexto7seg.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/xcounter.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/display4digit.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/counter4digit.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/display8digit.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/counter8digit.sv
  /home/vir/Lab6/Lab6.srcs/sources_1/new/bcdcounter.sv
}
read_xdc /home/vir/Lab6/Lab6.srcs/constrs_1/imports/Downloads/segdisplay.xdc
set_property used_in_implementation false [get_files /home/vir/Lab6/Lab6.srcs/constrs_1/imports/Downloads/segdisplay.xdc]

synth_design -top bcdcounter -part xc7a100tcsg324-1
write_checkpoint -noxdef bcdcounter.dcp
catch { report_utilization -file bcdcounter_utilization_synth.rpt -pb bcdcounter_utilization_synth.pb }
